name: Node.js Package

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: npm ci
      - run: npm test
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ZTNA }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ZTNA }}
          aws-region: us-east-2

      - name: Copy files to S3
        run: |
          branch_name=${GITHUB_REF##*/}
          echo ${{ secrets.AWS_S3_BUCKET }} | sed 's/./& /g' > S3_bucket.txt
          cat S3_bucket.txt
          S3_bucket=$(cat S3_bucket.txt | tr -d ' ')
          echo ${S3_bucket}
          component_name="relayagent"
          echo "checkout 1"
          path="s3://${S3_bucket}/${branch_name}/"
          aws s3 ls ${path}
          aws s3 ls s3://${{ secrets.AWS_S3_BUCKET }}/${branch_name}/
          exists=$(aws s3 ls s3://${{ secrets.AWS_S3_BUCKET }}/${branch_name}/)
          echo "checkout 2"
          if [ -z "$exists" ]
          then
              echo "checkout 3"
              version="${branch_name};build.1"
              echo $version > ${component_name}.version
              build=$(echo $version | awk -F';' '{print $2}')
          else
              echo "checkout 4"
              aws s3 cp --quiet ${path}/${component_name}.version ${component_name}.version
              version=`cat ${component_name}.version`
              build=$(echo $version | awk -F';' '{print $2}')
              build_current_version=$(echo $version | awk -F';' '{print $2}' | awk -F'.' '{print $2}')
              build_version=`expr ${build_current_version} + 1`
              echo "${branch_name};build.${build_version}" > ${component_name}.version
          fi
          echo "checkout 5"
          zip relay-agent-${branch_name}-${build_version}.zip relay-agent ${component_name}.version
          cp relay-agent-${branch_name}-${build_version}.zip relay-agent-${branch_name}-latest.zip
          exists=`aws s3 ls s3://${{secrets.AWS_S3_BUCKET}}/${branch_name}/`

          aws s3 cp relay-agent-${branch_name}-${build_version}.zip ${path} --acl public-read
          aws s3 cp relay-agent-${branch_name}-latest.zip ${path} --acl public-read
          aws s3 cp ${component_name}.version ${path}/${component_name}.version

          aws s3 cp relayagent_install.sh ${path} --acl public-read
          aws s3 cp relayagent_remove.sh ${path} --acl public-read
          aws s3 cp relayagent.service ${path} --acl public-read

          cat <<EOF >> relay-agent-${branch_name}-${build_version}.yaml
          version: ${branch_name}+${build}
          releaseDate: $(date +%Y-%m-%dT%H:%M:%S.%N)
          RelayAgentDownloadUrl: https://${{ secrets.AWS_S3_BUCKET }}.s3.us-east-2.amazonaws.com/${branch_name}/relay-agent-${branch_name}%2B${build}.zip
          RelayAgentServiceDownloadUrl : https://${{ secrets.AWS_S3_BUCKET }}.s3.us-east-2.amazonaws.com/${branch_name}/relayagent.service"
          EOF

          aws s3 cp relay-agent-${branch_name}-${build_version}.yaml ${path}

      
